set(CONFIG_PACKAGE_NAME "CANcheckedUpdater" CACHE STRING "")
set(CONFIG_PACKAGE_FILENAME "CANcheckedUpdater" CACHE STRING "")

set(CONFIG_TYCMD_BUILD OFF CACHE BOOL "")
set(CONFIG_TYCOMMANDER_BUILD OFF CACHE BOOL "")
set(CONFIG_TYUPDATER_EXECUTABLE "CANcheckedUpdater" CACHE STRING "")
set(CONFIG_TYUPDATER_NAME "CANchecked Updater" CACHE STRING "")

set(CONFIG_URL_WEBSITE "http://canchecked.de/" CACHE STRING "")
set(CONFIG_URL_BUGS "" CACHE STRING "")
