set(CONFIG_PACKAGE_NAME "DataLooper Updater" CACHE STRING "")
set(CONFIG_PACKAGE_FILENAME "DataLooperUpdater" CACHE STRING "")

set(CONFIG_TYCMD_BUILD OFF CACHE BOOL "")
set(CONFIG_TYCOMMANDER_BUILD OFF CACHE BOOL "")
set(CONFIG_TYUPDATER_EXECUTABLE "DataLooper Updater" CACHE STRING "")
set(CONFIG_TYUPDATER_NAME "DataLooper Updater" CACHE STRING "")

set(CONFIG_URL_WEBSITE "http://datalooperpedal.com/" CACHE STRING "")
set(CONFIG_URL_BUGS "" CACHE STRING "")
